development:
  adapter: postgresql
  encoding: unicode
  database: HN-trends_development

test:
  adapter: postgresql
  encoding: unicode
  database: HN-trends_test

production:
  adapter: postgresql
  encoding: unicode
  database: HN-trends_production
